### ISSUE TITLE
Chat doesn't scroll to bottom when joining

### ISSUE THREAD

**Issue by FunkyLoveCow** [Canop/miaou#13]
![Scroll To](http://i.imgur.com/NBggBLf.png)

When joining a chat room, it does not scroll to the very bottom of the chat room. It gets close (one to two messages, depending on length), but still leaves the very last message off the screen.

Edit: This occurs in Firefox but not Chrome. I figured this was important because I noticed this [note](https://github.com/Canop/miaou/blob/master/src/client-scripts/miaou.messagedisplay.js#L34) in the code.

**Comment by Canop** [comment]
fixed
