### ISSUE TITLE
Add option to disable changing the favicon on activity

### ISSUE THREAD

**Issue by ralt** [Canop/miaou#30]
The problem is that google chrome updates the favicon in the bookmarks bar when the tab updates. So even if you have miaou's tab pinned somewhere, you're easily distracted from work if your bookmark icons suddenly change colors.

**Comment by Canop** [comment]
This would be very easy to do. What bothers me is that options that almost nobody should change are highly disturbing for users. 

So I'd like to know how many people want this options. Please vote for it if you want it.
