### ISSUE TITLE
[Meta] TODO list

### ISSUE THREAD

**Issue by ralt** [Canop/miaou#36]
I think the todo list, currently "managed" in a miaou message, should be in a list of issues on github, or something more manageable. I propose github issues since the tool is already there :)

It would allow:

- a searchable list (github issues have: labels, search by labels, search by closed, etc)
- a way to assign items to someone
- a way to discuss these items
- something to reference to in the commits
- a way for people to propose new items, and being able to decline/accept them asynchronously (i.e. not in the chat)
- a way for people to choose something to contribute to (labels like "easy" could be added for people who want to start contributing)

Thoughts? I can translate the current todo list in github issues if you're lazy. Sure, that'd give a lot of issues, but at least it wouldn't be as volatile as the current way (a miaou message you manually maintain), and it would allow many more ways (shown above) to work.

**Comment by Canop** [comment]
We're using Trello now.
