### ISSUE TITLE
Filtering languages changes to default (or all) when switching tabs.

### ISSUE THREAD

**Issue by xbenjii** [Canop/miaou#51]
How to reproduce:
* Click English room filter
* Click tab you're on (or any other tab for that matter)

![](https://xbenjii.co.uk/i/REwme)
![](https://xbenjii.co.uk/i/s2l8J)
![](https://xbenjii.co.uk/i/wAjn8)

**Comment by Canop** [comment]
Bug confirmed

**Comment by Canop** [comment]
Fixed
