### ISSUE TITLE
Does this not work with nodejs? 

### ISSUE THREAD

**Issue by ViktorNova** [Canop/miaou#62]
The instructions for a regular install mention installing io.js. Does this not also work with node.js?
If it does, the installation instructions are misleading =)
https://github.com/Canop/miaou/blob/master/installation.md

**Comment by Canop** [comment]
This part was written before the merge back of io.js in node. Right now, Miaou should work on node.

I'll try it on node (and document it) as soon as possible.

(I lacked time for OSS in the last few months, mainly due to my already present son and the one who should be born in february).

**Comment by ViktorNova** [comment]
It seems to work with node v12, with the --harmony flag 
I will report back after it's been thoroughly tested

**Comment by Canop** [comment]
Miaou is now back to the new node (version >= 5).
