### ISSUE TITLE
Install instructions for OAuth are unclear

### ISSUE THREAD

**Issue by ViktorNova** [Canop/miaou#65]
Hi, I am having a hard time setting this up with Google Oauth - I can get the initial page to load, but when clicking the button to log in with Google, it's redirecting me to a blank white page. What am I missing here? I do have the API keys set up with Google.

**Comment by Canop** [comment]
Hard to tell without more (the logs for example). The problem is often a bad `server` parameter in config.js, or redis not started. Please come to https://dystroy.org/miaou/1 to discuss that (preferably in European day time).

**Comment by ViktorNova** [comment]
Thank you for pointing me in the right direction, I got it working. Apparently Google's oAuth takes a few minutes to fully register new callback URLs

**Comment by Canop** [comment]
@ViktorNova  You're not the first one disturbed by this, so I edited the documentation with a warning (see end of https://github.com/Canop/miaou/blob/master/installation.md#oauth2-providers)

**Comment by ViktorNova** [comment]
Excellent, this will probably help a lot of people out!
