### ISSUE TITLE
How to change presentation layer?

### ISSUE THREAD

**Issue by k0fi** [Canop/miaou#85]
Hello,

While miaou is excellent in functionalities, the presentation layer is just awful. To me it looks so 2004 and convoluted.
I just wanted to change the background color of a theme but got lost in myriad of scss files hidden behind crappy jade templates (sorry that's my opinion). 
So I'm wondering how can I just get rid of all these shenanigans and use a more straightforward approach like handlebar/css for presentation layer? What is the least cumbersome what to do that?

**Comment by Canop** [comment]
Hi, you'd better come to the chat (preferably during west-European hours) and discuss this with developers. For example here: https://dystroy.org/miaou/1
(or here if you speak French: https://dystroy.org/miaou/3)
But I'm afraid you'll be disappointed if you imagine a lazy magical way which would let you change things without even having to read and understand existing code, that's an application not a simple web page.
