### ISSUE TITLE
How to translate to other languages?

### ISSUE THREAD

**Issue by k0fi** [Canop/miaou#87]
Hi,
How can I add a new language to the existing options?
I could not find any hints or obvious 'locales' files to translate.

**Comment by Canop** [comment]
There's no translation yet of the chat interface. I deal every day with internationalization and localization of applications and I think it would be too much a burden for Miaou to support many languages, not really for the initial translation, which is always easy, but for the maintenance. **If** the usage of Miaou grows enough to justify it, of course we'll think about such an i18n facility.
